config/routes.rb
Rails.application.routes.draw do
  resources "recipes", only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < Contentful::Entry
  # Override if necessary
  # def title; end

  def content
    markdown.render description
  end

  def image_url
    photo.url.sub %r{\A//}, "https://"
  end

  def content_tags
    return if fields[:tags].blank?

    tags.map(&:name)
  end

  def chef_name
    return if fields[:chef].blank?

    chef.name
  end

  private

  def markdown
    @markdown ||= Redcarpet::Markdown.new(Redcarpet::Render::HTML)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from Content::Errors::NotFound, Contentful::NotFound, with: :not_found
  rescue_from Contentful::Unauthorized, with: :server_error

  def not_found
    render file: Rails.root.join("public/404.html"), status: :not_found
  end

  def server_error
    render file: Rails.root.join("public/500.html"), status: :internal_server_error
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = content_loader.recipes
  end

  def show
    @recipe = content_loader.entry params[:id]
  end

  private

  def content_loader
    @content_loader ||= Content::Loader.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipey</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag  'application',  media: 'all',  'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="p-1">
      <%= yield %>
    </div>
  </body>
</html>

app/views/recipes/index.html.erb
<h1 class="w-full text-xl text-green-900 text-center p-4 lg:text-3xl">
  Marley Spoon recipes of the day
</h1>
<div class="grid grid-cols-1 lg:grid-cols-2">
  <% @recipes.each do |recipe| %>
    <%= link_to "/recipes/#{recipe.id}", class: "recipe block p-3 hover:text-blue-800" do %>
      <div class="w-full">
        <%= image_tag recipe.image_url, class: "object-cover rounded-lg hover:shadow-md" %>
      </div>
      <div class="w-full text-center text-lg mt-1 lg:text-xl">
        <%= recipe.title %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/recipes/show.html.erb
<h1 class="title w-full text-xl text-green-900 text-center p-4 lg:text-3xl">
  <%= @recipe.title %>
  <%= link_to "Back", recipes_path,
      class: "float-right border border-gray-400 hover:border-gray-800 text-black text-sm py-1 px-3 rounded-md" %>
</h1>
<div class="p-2">
  <div class="image flex justify-center">
    <%= image_tag @recipe.image_url, class: "object-cover rounded-lg" %>
  </div>
  <div class="text-lg text-center mt-2 lg:text-xl">
    <% @recipe&.content_tags&.each do |tag| %>
      <span class="text-sm m-1 font-medium bg-green-100 py-1 px-2 rounded text-green-500 align-middle">
        <%= tag %>
      </span>
    <% end %>
    <div class="content mt-2"><%= sanitize @recipe.content %></div>
    <% if @recipe.chef_name %>
      <div class="mt-4"><em>Recipe by: <%= @recipe.chef.name %></em></div>
    <% end %>
  </div>
</div>